version: "3.9"

# Services
services:
  jupyter-server:
    image: cryptolabinc/heaan-stat:latest
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=kinankeren
    volumes:
      - jupyter-data:/root

# Volume
volumes:
  jupyter-data:
    driver: local
